# 라이브러리 버전---------------------------------------------------------------------------------------------------------------
[versions]
# kotlin
kotlin = "1.8.20"
kotlinCompilerExtension = "1.4.6"
kotlinxCoroutines = "1.7.0"
kotlinxSerializationJson = "1.5.0"
kotlinxDateTime = "0.4.0"

androidGradlePlugin = "8.0.1"
androidDesugarJdkLibs = "2.0.3"

# androidx
androidxCore = "1.10.0"
androidxActivity = "1.7.1"
androidxFragment = "1.5.7"
androidxNavigation = "2.5.3"
androidxComposeBom = "2023.04.01"
androidxConcurrentFutures = "1.1.0"
androidxLifecycle = "2.6.1"
androidxDatastore = "1.0.0"
androidxWork = "2.8.1"
androidxRoom = "2.5.1"
androidxRecyclerview = "1.3.0"
androidxRecyclerviewSelection = "1.1.0"
androidxAppcompat = "1.6.1"
androidxPreferenceKtx = "1.2.0"
androidxConstraintlayout = "2.1.4"
androidxConstraintlayoutCompose = "1.0.1"
androidxGridlayout = "1.0.0"
androidxHilt = "2.45"
androidxHiltNavigationCompose = "1.0.0"
androidxHiltWork = "1.0.0"
androidxHiltNavigationFragment = "1.0.0"
androidxWindowManager = "1.0.0"
androidXTestEspresso = "3.5.1"
androidXTestRunner = "1.5.2"
androidXTestRules = "1.5.0"
androidXTestCore = "1.5.0"
androidXTestAnnotation = "1.0.1"
androidXTestJUnit = "1.1.5"
androidXPaging = "3.1.1"

androidXTestTruth = "1.5.0"
androidXTestOrchestra = "1.4.2"

jUnit = "4.12"

material = "1.8.0"
glide = "4.15.1"
gms = "4.3.15"
retrofit2 = "2.9.0"
retrofit2KotlinxSerializationJson = "1.0.0"

okhttp3 = "4.10.0"

flexbox = "3.0.0"

compileSdk = "33"
targetSdk = "33"
minSdk = "28"

#firebase
firebaseCrashlytics = "2.9.4"
firebaseBom = "31.2.3"

# 라이브러리 의존성------------------------------------------------------------------------------------------------------------------------
[libraries]
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }

# androidX--------------------------------------------------------------------------------------------------------------------

# compose --------------------------------------------------------------------------------------------------------------------------------
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidxConstraintlayoutCompose" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-ui-testAndroidTestImplementation = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-testManifestdebugImplementation = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-toolingDebugImplementation = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidxPreferenceKtx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragment" }
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivity" }

androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidXPaging" }
# androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidxActivity" }

androidx-datastore-core = { group = "androidx.datastore", name = "datastore", version.ref = "androidxDatastore" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDatastore" }

# 미사용
# androidx-window-manager = { module = "androidx.window:window", version.ref = "androidxWindowManager" }

androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "androidxLifecycle" }
androidx-lifecycle-compilerKapt = { group = "androidx.lifecycle", name = "lifecycle-compiler", version.ref = "androidxLifecycle" }

androidx-navigation-testingAndroidTestImplementation = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidxNavigation" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidxNavigation" }
androidx-navigation-dynamic = { group = "androidx.navigation", name = "navigation-dynamic-features-fragment", version.ref = "androidxNavigation" }

androidx-work-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWork" }
androidx-work-testingAndroidTestImplementation = { group = "androidx.work", name = "work-testing", version.ref = "androidxWork" }

androidx-room-compileKapt = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }

androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidxRecyclerview" }
androidx-concurrentfutures = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "androidxConcurrentFutures" }

androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintlayout" }

# test------------------------------------------------------------------------------------------------------------------------
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidXTestEspresso" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidXTestRunner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidXTestRules" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidXTestCore" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidXTestCore" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidXTestJUnit" }
androidx-test-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidXTestJUnit" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidXTestOrchestra" }
androidx-test-truth = { module = "androidx.test.ext:truth", version.ref = "androidXTestTruth" }

junit = { module = "junit:junit", version.ref = "jUnit" }

android-flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }

# firebase--------------------------------------------------------------------------------------------------------------------
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }

# hilt------------------------------------------------------------------------------------------------------------------------
androidx-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "androidxHilt" }
androidx-hilt-android-testingAndroidTestImplementation = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "androidxHilt" }
androidx-hilt-compilerKapt = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "androidxHilt" }

# with Navigation---------------------------------------
androidx-hilt-navigation-fragment = { group = "androidx.hilt", name = "hilt-navigation-fragment", version.ref = "androidxHiltNavigationFragment" }

# with WorkManager----------------------------------
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidxHiltWork" }
androidx-hilt-work-compilerKapt = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidxHiltWork" }

# kotlin--------------------------------------------------------------------------------------------------------------
kotlin-stdlib-jdk7 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-stdlib-root = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-testImplementation = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDateTime" }

# retrofit2--------------------------------------------------------------------------------------------------------------
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
retrofit-kotlinx-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationJson" }

# okhttp3--------------------------------------------------------------------------------------------------------------
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
okhttp-logginginterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3" }

# glide--------------------------------------------------------------------------------------------------------------
glide-main = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compilerKapt = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

# material--------------------------------------------------------------------------------------------------------------
material-main = { module = "com.google.android.material:material", version.ref = "material" }

android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

kotlin-reflection = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

# 라이브러리들을 묶어서 한번에 선언------------------------------------------------------------------------------------------------------------------------
[bundles]

composes = ["androidx-compose-bom",
    "androidx-compose-runtime-livedata",
    "androidx-compose-runtime",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-ui-util",
    "androidx-compose-ui",
    "androidx-compose-foundation",
    "androidx-compose-foundation-layout"]

uiAndroidx = ["androidx-appcompat", "androidx-preference-ktx", "androidx-core-ktx", "androidx-fragment", "androidx-activity",
    "androidx-recyclerview", "androidx-constraintlayout", "androidx-constraintlayout-compose", "androidx-activity-compose",
]

lifecycles = ["androidx-lifecycle-livedata-ktx", "androidx-lifecycle-runtime-ktx", "androidx-lifecycle-viewmodel-ktx",
    "androidx-lifecycle-viewmodel-savedstate", "androidx-lifecycle-viewmodel-compose", "androidx-lifecycle-runtime-compose"]

retrofits = ["retrofit-core", "retrofit-kotlinx-serialization"]

navigations = ["androidx-navigation-fragment-ktx", "androidx-navigation-ui-ktx", "androidx-navigation-compose", "androidx-navigation-dynamic"]

kotlins = ["kotlin-stdlib-jdk7", "kotlin-stdlib-jdk8", "kotlin-stdlib-root", "kotlinx-coroutines-android", "kotlinx-serialization-json",
    "kotlinx-datetime", "kotlin-reflection"]

materials = ["material-main", "androidx-compose-material3", "androidx-compose-material3-windowSizeClass"]

glides = ["glide-main"]

firebases = ["firebase-bom", "firebase-crashlytics"]

hilts = ["androidx-hilt-navigation-compose", "androidx-hilt-android", "androidx-hilt-navigation-fragment",
    "androidx-hilt-work", "androidx-hilt-navigation-compose"]

rooms = ["androidx-room-ktx", "androidx-room-runtime"]

dataStores = ["androidx-datastore-core", "androidx-datastore-preferences"]

workManagers = ["androidx-work-ktx"]

testUIs = ["androidx-test-espresso-core", "androidx-test-runner", "androidx-test-rules", "androidx-test-core",
    "androidx-test-core-ktx", "androidx-test-junit", "androidx-test-junit-ktx", "androidx-test-truth", "junit"]

# ------------------------------------------------------------------------------------------------------------------------
[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }

firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
gms = { id = "com.google.gms.google-services", version.ref = "gms" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "androidxHilt" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
# for kotlin-serialization
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
# for Navigation
nav-safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidxNavigation" }

kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }